Allow compiling with markdown3
Currently compilation fails with:

    /build/src/classes/renderer/markdown.c:191:20: error: variable or field 'flags' declared void

According to comment [1], markdown3 introduces backward
incompatibility with respect to document flags.

This commit adds conditionally compiled code that allows building
pdfpc with both markdown versions 2 and 3.

The used cmake operator VERSION_GREATER_EQUAL requires cmake 3.7 so we
bump minimal cmake version requirement.

Fixes #682

[1]: https://github.com/pdfpc/pdfpc/issues/682#issuecomment-1931300154